import { describe, expect, it } from "vitest";
import {
  DISPLAY_FRAME_SANDBOX,
  buildDisplayDocument,
  buildOuterCsp,
  buildOuterHtml,
} from "./frames.js";

const CSP_SOURCE = "vscode-webview://abc";
const NONCE = "0123456789abcdef";

describe("表示フレームにスクリプトは無い", () => {
  it("sandbox は空（allow-scripts を含まない）", () => {
    expect(DISPLAY_FRAME_SANDBOX).toBe("");
    expect(DISPLAY_FRAME_SANDBOX).not.toContain("allow-scripts");
  });

  it("外側の HTML に書かれている表示フレームの sandbox にも allow-scripts が無い", () => {
    // 定数が正しくても、埋める側が別の値を書いていたら意味が無い。
    const html = buildOuterHtml(CSP_SOURCE, NONCE);
    const displayFrame = /<iframe id="showme-display"[^>]*>/.exec(html)?.[0] ?? "";
    expect(displayFrame).not.toBe("");
    expect(displayFrame).toContain('sandbox=""');
    expect(displayFrame).not.toContain("allow-scripts");
  });
});

describe("外側の CSP", () => {
  const csp = buildOuterCsp(CSP_SOURCE, NONCE);

  it("default-src 'none' から始まる", () => {
    expect(csp.startsWith("default-src 'none'")).toBe(true);
  });

  it("frame-src は 'none'（src 付きの孫フレームを作れない）", () => {
    // 2C Task 0 の実測: `srcdoc` は frame-src の対象外なので我々の2枚は動く。
    // `src` 付きの孫は落ちる。以前の `'self' data:` は data: の孫を1つ開けていた。
    expect(csp).toContain("frame-src 'none'");
    expect(csp).not.toContain("frame-src 'self'");
    expect(csp).not.toContain("frame-src data:");
  });

  it("script-src は nonce だけ（unsafe-eval も unsafe-inline も無い）", () => {
    expect(csp).toContain(`script-src 'nonce-${NONCE}'`);
    expect(csp).not.toContain("unsafe-eval");
    expect(csp).not.toContain("wasm-unsafe-eval");
    expect(csp).not.toContain("script-src 'unsafe-inline'");
  });

  it("connect-src / object-src / form-action / base-uri が 'none'", () => {
    for (const directive of [
      "connect-src 'none'",
      "object-src 'none'",
      "form-action 'none'",
      "base-uri 'none'",
    ]) {
      expect(csp, directive).toContain(directive);
    }
  });

  it("img-src と media-src はリモートを許さない（data: と自分の出所だけ）", () => {
    expect(csp).toContain(`img-src data: ${CSP_SOURCE}`);
    expect(csp).toContain("media-src data:");
    expect(csp).not.toContain("img-src https:");
    expect(csp).not.toContain("http:");
  });

  it("webrtc 'block' は書いてあるが、これは層ではない", () => {
    // この Chromium では no-op（2C Task 0 の実測）。指令は将来のために残すが、
    // **防御として数えない**。ここで固定しているのは「書いてあること」だけである。
    expect(csp).toContain("webrtc 'block'");
  });
});

describe("外側の HTML は静的である", () => {
  it("同じ nonce と出所なら、いつ呼んでも同じ文字列", () => {
    // エージェント由来の値が入る余地が無いことの、いちばん素朴な言い方。
    expect(buildOuterHtml(CSP_SOURCE, NONCE)).toBe(buildOuterHtml(CSP_SOURCE, NONCE));
  });

  it("なりすまし対策の帯を外側が描いている", () => {
    const html = buildOuterHtml(CSP_SOURCE, NONCE);
    expect(html).toContain("This content was generated by an agent");
    // 帯はスクロールで消えない位置（flex の固定枠）に置く。
    expect(html).toContain("showme-banner");
  });

  it("中身はプロパティ代入で入る（srcdoc 属性に値を埋め込まない）", () => {
    const html = buildOuterHtml(CSP_SOURCE, NONCE);
    // 空の iframe を置いて、あとから `.srcdoc = …` する形であること。
    // 受領確認を足したときに `String(data.html)` を変数に切り出したので、
    // 代入の形そのものを見る。**属性ではなくプロパティに入っている**ことが要点。
    expect(html).toContain("display.srcdoc = html");
    expect(html).not.toMatch(/<iframe[^>]*srcdoc=/);
  });

  it("受け取ったメッセージの送信元を検証している", () => {
    const html = buildOuterHtml(CSP_SOURCE, NONCE);
    // 表示フレームからは何も受け取らない（今はスクリプトが無くて送れないが、
    // 将来の変更で穴が開かないよう最初から区別する）。
    expect(html).toContain("event.source === display.contentWindow");
  });

  it("すべての script に nonce が付いている", () => {
    const html = buildOuterHtml(CSP_SOURCE, NONCE);
    const scripts = html.match(/<script[^>]*>/g) ?? [];
    expect(scripts.length).toBeGreaterThan(0);
    for (const tag of scripts) {
      expect(tag, tag).toContain(`nonce="${NONCE}"`);
    }
  });
});

describe("表示フレームには読める既定がある（実地で黒地に黒になった）", () => {
  it("baseline が前置され、エージェントの HTML は後ろに来る", () => {
    const html = buildDisplayDocument("<p>x</p>");
    expect(html).toContain("color-scheme");
    expect(html).toContain("<p>x</p>");
    // **後から来た指定が勝つ。** エージェントが配色を書いたらそちらが有効になる。
    expect(html.indexOf("color-scheme")).toBeLessThan(html.indexOf("<p>x</p>"));
  });

  it("baseline は我々のリテラルだけで、引数を差し込まない", () => {
    // 入力は1箇所にしか現れない（テンプレートに埋め込む口を作らない）。
    const out = buildDisplayDocument("SHOWME_MARKER");
    expect(out.split("SHOWME_MARKER").length - 1).toBe(1);
  });

  it("テーマ変数（var）を使わずにテーマへ追随する", () => {
    // `var()` は sanitize-css が意図的に禁止している（設計 D32）ので、
    // baseline も同じ規則の中で書く。CSS のシステム色を使う。
    const html = buildDisplayDocument("<p>x</p>");
    expect(html).not.toContain("var(--vscode");
    expect(html).toContain("Canvas");
    expect(html).toContain("CanvasText");
  });

  it("エージェントが背景を指定したらそちらが後ろに来る", () => {
    const html = buildDisplayDocument("<style>body{background-color:#fff}</style>");
    expect(html.indexOf("color-scheme")).toBeLessThan(html.indexOf("#fff"));
  });

  it("表の罫線が既定で引かれる（border-collapse が入っている）", () => {
    expect(buildDisplayDocument("")).toContain("border-collapse: collapse");
  });
});
